### ISSUE TITLE
[BUG]Successful connection in tableau but Table list is not displayed

### ISSUE THREAD

**Issue by taki-liber** [aws/amazon-documentdb-jdbc-driver#369] opened 2022-07-12 05:32 UTC
## Environment
- DocumentDB JDBC driver version:
    - documentdbjdbc-1.2.5.taco
    - documentdb-jdbc-1.2.5-all.jar
- DocumentDB server version:docdb 4.0.0
- OS: Windows 10 64-bit (However, there is no problem with MAC PC)
- BI Tool or client name: Tableau Desktop
- BI Tool or client version:20222.22
- Java version (if known): 1.8.0_333

---

## Problem Description
1. Steps to reproduce:
 within ec2 instance in VPC
 With TACO and  jdbc  in tableau connect to Amazon documentDB

2. Expected behaviour:
Overview of tables in schema

3. Actual behaviour:
Table list is not displayed
![tableau_amazon_document_dbのテーブルー覧が表示されない](https://user-images.githubusercontent.com/15013488/178415160-17e80e1c-0a2b-430a-b718-b095de35a159.png)

4. Error message/stack trace:
No error message

5. Any other details that can be helpful:
there is no problem with MAC PC.

---

## Screenshots
- If applicable, add screenshots to help explain your problem.
![tableau_バージョン](https://user-images.githubusercontent.com/15013488/178415619-b4d5268a-6aae-4cf4-a74b-a3f44c522935.png)

---

## JDBC log
- Add related JDBC log entries here.
Tableau Desktop log
[log.txt](https://github.com/aws/amazon-documentdb-jdbc-driver/files/9089752/log.txt)

**Comment by MANDLA15** [comment] 2022-07-19 09:34
I am also experiencing the same issue.

**Comment by MANDLA15** [comment] 2022-07-19 10:56
@taki-liber you can use the older version of the driver 1.2.3. It works fine.

**Comment by andiemontoyeah** [comment] 2022-07-19 15:39
Thanks both for reporting and adding your findings on the issue. We have identified the cause and have a fix in review #355. For now, the issue should not be present in versions <= 1.2.3 which otherwise has same features as latest aside from some dependency updates. 
We will post an update when a new version is released w/ the fix. Thank you!

**Comment by andiemontoyeah** [comment] 2022-07-22 22:50
Bug fix for this issue was released as part of https://github.com/aws/amazon-documentdb-jdbc-driver/releases/tag/v1.3.0. Thanks @taki-liber and @MANDLA15 for investigating and reporting the issue!

**Closed as completed by andiemontoyeah** 2022-07-22 22:50 UTC
Labels: bug
